sudo: false
language: python
python:
  - "2.7"

install:
  - pip install tox

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOX_ENV=py27-eventlet174-pytest273-test
  - TOX_ENV=py27-eventlet174-pytest287-test
  - TOX_ENV=py27-eventlet174-pytest291-test
  - TOX_ENV=py27-eventlet184-pytest273-test
  - TOX_ENV=py27-eventlet184-pytest287-test
  - TOX_ENV=py27-eventlet184-pytest291-test
  - TOX_ENV=py27-eventlet190-pytest273-test
  - TOX_ENV=py27-eventlet190-pytest287-test
  - TOX_ENV=py27-eventlet190-pytest291-test
  - TOX_ENV=py33-eventlet174-pytest273-test
  - TOX_ENV=py33-eventlet174-pytest287-test
  - TOX_ENV=py33-eventlet174-pytest291-test
  - TOX_ENV=py33-eventlet184-pytest273-test
  - TOX_ENV=py33-eventlet184-pytest287-test
  - TOX_ENV=py33-eventlet184-pytest291-test
  - TOX_ENV=py33-eventlet190-pytest273-test
  - TOX_ENV=py33-eventlet190-pytest287-test
  - TOX_ENV=py33-eventlet190-pytest291-test
  - TOX_ENV=py34-eventlet174-pytest273-test
  - TOX_ENV=py34-eventlet174-pytest287-test
  - TOX_ENV=py34-eventlet174-pytest291-test
  - TOX_ENV=py34-eventlet184-pytest273-test
  - TOX_ENV=py34-eventlet184-pytest287-test
  - TOX_ENV=py34-eventlet184-pytest291-test
  - TOX_ENV=py34-eventlet190-pytest273-test
  - TOX_ENV=py34-eventlet190-pytest287-test
  - TOX_ENV=py34-eventlet190-pytest291-test

script:
  - tox -e $TOX_ENV
